apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssheikh24-eta-deploy
  labels:
    app: ssheikh24-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssheikh24-eta-app
  template:
    metadata:
      labels:
        app: ssheikh24-eta-app
    spec:
      containers:
      - name: ssheikh24-eta-container
        image: ssheikh24/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ssheikh24-eta-np-service
  labels:
    app: ssheikh24-eta-np-app
spec:
  selector:
    app: ssheikh24-eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
